import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { Locale, routing } from '@/i18n/routing';
import { ThemeProvider } from 'next-themes';
import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'HealJai | ฮีลใจ',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <NextIntlClientProvider messages={messages}>
        <body className='h-screen bg-[url("/light-sky.jpg")] dark:bg-[url("/dark-sky.jpg")] bg-cover bg-fixed antialiased'>
          <ThemeProvider attribute='class' defaultTheme='light'>
            <Navbar locale={(await params).locale} />
            <main className='h-full max-w-[85rem] mx-auto pt-[4rem] px-4 lg:px-8'>{children}</main>
          </ThemeProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
